version: '3'

services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80 # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy:/data
      - ./caddy_linux_arm64_custom_duckdns:/usr/bin/caddy
    networks:
      - caddy
    env_file:
      - ./caddy.env
      - ./duckdns.env
    environment:
      - LOG_DIR=/data

networks:
  caddy:
    name: caddy
volumes:
  caddy:
    external: true
