services:
  caddy:
    image: ghcr.io/hybras/caddy:latest
    container_name: caddy
    restart: always
    ports:
      - 80:80 # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - caddy:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - caddy
    env_file:
      - ./caddy.env
      - ./duckdns.env
    environment:
      - LOG_DIR=/data
      - CADDY_INGRESS_NETWORKS=caddy
    mem_limit: 40MiB
    dns:
      - 1.1.1.1
      - 8.8.8.8

networks:
  caddy:
    name: caddy
volumes:
  caddy:
    name: caddy
