networks:
  rimgo:
    name: rimgo
  caddy:
    external: true


services:
  rimgo:
    image: quay.io/pussthecatorg/rimgo
    container_name: rimgo
    environment:
      PORT: 80
    restart: unless-stopped
    mem_limit: 40MiB
    networks:
      - rimgo
      - caddy
