networks:
  gitea:
    name: gitea

volumes:
  gitea:
    name: gitea
  gitea-db:
    name: gitea-db

services:
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    restart: always
    networks:
      - gitea
    volumes:
      - gitea:/data
    ports:
      - "2222:22"
    depends_on:
      - gitea-db
    mem_limit: 100MiB
    environment:
      TZ: 'America/New_York'

  gitea-db:
    image: postgres:14
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - gitea-db:/var/lib/postgresql/data
    mem_limit: 80MiB
