volumes:
  pihole:
    name: pihole

networks:
  pihole:
    name: pihole
  caddy:
    external: true

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/

services:
  pihole:
    image: pihole/pihole:2026.02.0
    container_name: pihole
    hostname: pihole
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    environment:
      TZ: 'America/New_York'
      FTLCONF_dns_upstreams: '208.67.220.220;1.1.1.1;8.8.8.8'
    env_file:
      - webpassword.env
    volumes:
      - 'pihole:/etc/pihole/'
    restart: unless-stopped
    networks:
      - pihole
      - caddy
