networks:
  nextcloud:
    name: nextcloud
  caddy:
    external: true

volumes:
  nextcloud:
  data:
  cache:
  db:
  apps:
  config:


services:
  cache:
    image: redis:alpine
    container_name: nextcloud-cache
    restart: unless-stopped
    networks:
      - nextcloud
    volumes:
      - cache:/data
    mem_limit: 20MiB

  db:
    image: mariadb:10.5
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin --binlog-format=ROW
    networks:
      - nextcloud
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./db.env
    mem_limit: 200MiB
  cron:
    image: nextcloud
    container_name: nextcloud-cron
    restart: always
    volumes:
      - nextcloud:/var/www/html:rw
    networks:
      - nextcloud
    environment:
      - NEXTCLOUD_INIT_LOCK=true
    entrypoint: /cron.sh
    depends_on:
      - db
      - cache
    mem_limit: 20MiB
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - nextcloud
      - caddy
    depends_on:
      - cache
      - db
    volumes:
      - nextcloud:/var/www/html:rw
      - apps:/var/www/html/custom_apps
      - config:/var/www/html/config
      - data:/var/www/html/data
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - REDIS_HOST=cache
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.hybras.dev
      - NEXTCLOUD_INIT_LOCK=true
      - MYSQL_HOST=db
    env_file:
      - ./db.env
      - ./nextcloud_admin_password.env
    mem_limit: 200MiB

secrets:
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.txt
