version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    mem_limit: 40MiB
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
