volumes:
  headscale: {}

services:
  headscale:
    dns: []
    image: docker.io/headscale/headscale:0.28.0
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/run/headscale
    ports:
      - '8080:8080'
      - '9090:9090'
    volumes:
      - headscale:/var/lib/headscale
      - ./config.yaml:/etc/headscale/config.yaml:ro
    command: serve
    healthcheck:
      test: ['CMD', 'headscale', 'health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
