volumes:
  headscale: { name: headscale }
  headplane: { name: headplane }

networks:
  headscale:
    name: headscale
  caddy:
    external: true

secrets:
  headplane-cookie-secret:
    file: ./cookie_secret

services:
  headscale:
    dns: []
    image: docker.io/headscale/headscale:0.28.0
    restart: unless-stopped
    container_name: headscale
    read_only: true
    tmpfs:
      - /var/run/headscale
    ports:
      - '127.0.0.1:9090:9090'
    volumes:
      - headscale:/var/lib/headscale
      - ./headscale.yaml:/etc/headscale/config.yaml:ro
    command: serve
    healthcheck:
      test: ['CMD', 'headscale', 'health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - headscale
      - caddy
    labels:
      me.tale.headplane.target: headscale
  headplane:
    image: ghcr.io/tale/headplane:0.6.2
    container_name: headplane
    restart: unless-stopped
    volumes:
      - headplane:/var/lib/headplane
      - ./headplane.yaml:/etc/headplane/config.yaml:ro
      - ./headscale.yaml:/etc/headscale/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - headplane-cookie-secret
    networks:
      - headscale
      - caddy
    depends_on:
      headscale:
        condition: service_healthy
