volumes:
  headscale: { name: headscale }

networks:
  headscale:
    name: headscale
  caddy:
    external: true

services:
  headscale:
    dns: []
    image: docker.io/headscale/headscale:0.28.0
    restart: unless-stopped
    container_name: headscale
    read_only: true
    tmpfs:
      - /var/run/headscale
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:9090:9090'
    volumes:
      - headscale:/var/lib/headscale
      - ./headscale.yaml:/etc/headscale/config.yaml:ro
    command: serve
    healthcheck:
      test: ['CMD', 'headscale', 'health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
